<a href="https://colab.research.google.com/github/ruhullahil/gcolab/blob/master/backpropagation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np


def sigmoyed(x):

 return 1.0/(1+np.exp(x))


def sigmoid_der(self, x):
        return x * (1 - x)

def 
  


In [0]:
_input = np.array([0,1,0])
h1= np.random.rand(3,3)
h2 = np.random.rand(3,2)
h3 = np.random.rand(2,1)
target = np.array([1])
epcth =100;
eta = 0.01

  




In [0]:
import numpy as np

class Perceptron:
    def __init__(self, number_of_inputs):
        self.weights = np.random.rand(number_of_inputs, 1)
        print("Initial Weights:\n", self.weights, end='\n\n')
    
    def sigmoid(x):
        return 1.0 / (1.0 + np.exp(-x))
    
    def sigmoid_der(self, x):
        return x * (1 - x)
    
    def feedForward(self, inputs):
        return np.dot(inputs, self.weights)
    
    def backPropagation(self, output, target, learning_rate=0.1):
        error = target - output
        error = np.sum(np.square(error)/2)
        print("Error", error)
        
        # dEtotal/dOut
        dEtotal_by_dOut = (target - output)
        # dOut/dNet
        dOut_by_dNet = self.sigmoid_der(output)
        
        dEtotal_by_w = np.array(dEtotal_by_dOut*dOut_by_dNet*self.weights)
        self.weights -= learning_rate * dEtotal_by_w
        
        print("Updated Weights:\n", self.weights, end="\n\n")
        
    def run(self, inputs, target, iters):
        for i in range(iters):
            self.backPropagation(self.feedForward(inputs), target)


P = Perceptron(3)
P.run([1, 2, 3], 0.5, 10)

Initial Weights:
 [[0.41845286]
 [0.28149052]
 [0.27959617]]

Error 0.8714935835337274
Updated Weights:
 [[0.33597266]
 [0.22600662]
 [0.22448566]]

Error 0.4621862165487568
Updated Weights:
 [[0.31418918]
 [0.21135302]
 [0.20993067]]

Error 0.37557338032008686
Updated Weights:
 [[0.30054277]
 [0.20217316]
 [0.2008126 ]]

Error 0.32588834711580733
Updated Weights:
 [[0.29079421]
 [0.19561537]
 [0.19429894]]

Error 0.29255264720318386
Updated Weights:
 [[0.2833403 ]
 [0.19060117]
 [0.18931848]]

Error 0.26827673495477145
Updated Weights:
 [[0.27739299]
 [0.18660046]
 [0.18534469]]

Error 0.24966155305160026
Updated Weights:
 [[0.27250592]
 [0.18331296]
 [0.18207931]]

Error 0.2348658607232083
Updated Weights:
 [[0.26840205]
 [0.18055231]
 [0.17933725]]

Error 0.22279040711656928
Updated Weights:
 [[0.26489795]
 [0.17819513]
 [0.17699593]]

Error 0.21273199300170964
Updated Weights:
 [[0.26186617]
 [0.17615567]
 [0.17497019]]



In [0]:
# first neural network with keras make predictions
from numpy import loadtxt
from keras.models import Sequential
from keras.layers import Dense
# load the dataset
dataset = loadtxt('pima-indians-diabetes.csv', delimiter=',')
# split into input (X) and output (y) variables
X = dataset[:,0:8]
y = dataset[:,8]
# define the keras model
model = Sequential()
model.add(Dense(12, input_dim=8, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
# compile the keras model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
# fit the keras model on the dataset
model.fit(X, y, epochs=150, batch_size=10, verbose=0)
# make class predictions with the model
predictions = model.predict_classes(X)
# summarize the first 5 cases
for i in range(5):
	print('%s => %d (expected %d)' % (X[i].tolist(), predictions[i], y[i]))

Using TensorFlow backend.


OSError: ignored