<a href="https://colab.research.google.com/github/ruhullahil/gcolab/blob/master/Copy_of_Untitled.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
m = 3
n = 3
p = 0
q = 4
r = 0

In [0]:
X1 = [[m, r, m, p, r], 
      [n, p, p, n, n]]

X2 = [[m, p, q, m, m], 
      [r, q, m, q, m]]

In [0]:
X1 = np.array(X1)
X2 = np.array(X2)
N = X1.shape[1]

In [0]:
print(X1)
print()
print(X2)
print()
print(f'Number of elements {N}')

[[3 0 3 0 0]
 [3 0 0 3 3]]

[[3 0 4 3 3]
 [0 4 3 4 3]]

Number of elements 5


In [0]:
mu1 = (np.sum(X1, axis=1)/N)
mu2 = (np.sum(X2, axis=1)/N)

mu1 = mu1.reshape(2, 1)
mu2 = mu2.reshape(2, 1)

In [0]:
print('MU_1=\n', mu1)
print()
print('MU_2=\n', mu2)

MU_1=
 [[1.2]
 [1.8]]

MU_2=
 [[2.6]
 [2.8]]


In [0]:
x1MinusMU = X1 - mu1
x2MinusMU = X2 - mu2

In [0]:
print(x1MinusMU)
print()
print(x2MinusMU)

[[ 1.8 -1.2  1.8 -1.2 -1.2]
 [ 1.2 -1.8 -1.8  1.2  1.2]]

[[ 0.4 -2.6  1.4  0.4  0.4]
 [-2.8  1.2  0.2  1.2  0.2]]


In [0]:
S1 = np.matmul(x1MinusMU, x1MinusMU.T)/(N-1)
S2 = np.matmul(x2MinusMU, x2MinusMU.T)/(N-1)

In [0]:
print('S_1=\n', S1)
print()
print('S_2=\n', S2)

S_1=
 [[ 2.7  -0.45]
 [-0.45  2.7 ]]

S_2=
 [[ 2.3  -0.85]
 [-0.85  2.7 ]]


In [0]:
Sw = S1 + S2
print('Sw=\n', Sw)

Sw=
 [[ 5.  -1.3]
 [-1.3  5.4]]


In [0]:
invSw = np.linalg.inv(Sw)
print(invSw)

[[0.21335441 0.0513631 ]
 [0.0513631  0.19755038]]


In [0]:
wStar = np.matmul(invSw, mu1 - mu2)

In [0]:
print('w*\n', wStar)

w*
 [[-0.35005927]
 [-0.26945871]]
